export function createFileBrowser({dialog,send,onResize,onTerminal}){
 const $=s=>document.querySelector(s),sidebar=$('#file-sidebar'),tree=$('#file-tree'),pathInput=$('#file-path'),toggle=$('#terminal-files-toggle'),editor=$('#file-editor'),input=$('#file-content'),status=$('#file-editor-status');
 const pending=new Map(),cache=new Map(),expanded=new Set();let active=false,sequence=0,generation=0,root='/',current=null,baseline='',saving=false,opening=false,confirmResolve=null;
 const bytes=s=>new TextEncoder().encode(s).length;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 function button(text,label,fn){const b=el('button','',text);b.type='button';b.setAttribute('aria-label',label);b.title=label;b.addEventListener('click',fn);return b;}
 function icon(kind){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 20 20');svg.setAttribute('aria-hidden','true');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',kind==='directory'?'M2.5 5.5h5l2-2h7.5v13h-15z':kind==='link'?'M8 12l4-4M7 9l-1 1a3 3 0 004 4l1-1M9 7l1-1a3 3 0 014 4l-1 1':'M5 2.5h7l3 3v12H5zM12 2.5v4h3M7.5 10h5M7.5 13h5');svg.append(path);return svg;}
 function dirty(){return !!current&&!current.readOnly&&input.value!==baseline;}
 function note(message,error=false){status.textContent=message;status.classList.toggle('is-error',error);}
 function summary(){if(!current)return;const size=bytes(input.value)+(current.lineEnding==='crlf'?(input.value.match(/\n/g)||[]).length:0),lines=input.value.split('\n').length;$('#file-meta').textContent=`UTF-8 · ${current.lineEnding.toUpperCase()} · ${lines} 行 · ${(size/1024).toFixed(1)} KiB`;$('#file-save').disabled=!active||current.readOnly||saving||!dirty()||size>262144;$('#file-reload').disabled=!active||saving;$('#file-dirty').hidden=!dirty();if(size>262144)note('内容超过 256 KiB，请缩小后保存。',true);}
 function setSidebar(show){sidebar.hidden=!show;$('#file-resizer').hidden=!show;toggle.setAttribute('aria-expanded',String(show));dialog.classList.toggle('files-visible',show);requestAnimationFrame(onResize);}
 function view(which){const file=which==='file'&&!!current;editor.hidden=!file;$('#terminal-panel').hidden=file;$('#terminal-tab').classList.toggle('active',!file);$('#file-tab').classList.toggle('active',file);$('#terminal-tab').setAttribute('aria-selected',String(!file));$('#file-tab').setAttribute('aria-selected',String(file));if(!file){requestAnimationFrame(()=>{onResize();onTerminal();});}}
 function request(action,path,extra={}){if(!active)return Promise.reject(Error('SSH 连接已断开，请重新连接'));if(pending.size>=3)return Promise.reject(Error('已有文件操作正在进行'));const id='file_'+(++sequence);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('文件操作超时；若正在保存，请重新读取确认结果'));},action==='save'?50000:24000);pending.set(id,{resolve,reject,timer});try{send(JSON.stringify({type:'file',id,action,path,...extra}));}catch(e){clearTimeout(timer);pending.delete(id);reject(e);}});}
 function receive(message){const job=pending.get(message.id);if(!job)return;pending.delete(message.id);clearTimeout(job.timer);if(message.ok)job.resolve(message.data);else{const e=Error(message.error||'文件操作未完成');e.code=message.code;job.reject(e);}}
 function treeNote(message,error=false){$('#file-tree-status').textContent=message;$('#file-tree-status').classList.toggle('is-error',error);}
 async function load(path=root,{navigate=false,offset=0,action='list'}={}){const epoch=generation;treeNote('正在读取…');try{const data=await request(action,path,{offset});if(epoch!==generation)return;const previous=cache.get(data.path);cache.set(data.path,{...data,entries:offset&&previous?[...previous.entries,...data.entries]:data.entries});if(navigate||action==='home'){root=data.path;pathInput.value=root;}expanded.add(data.path);render();treeNote(`${data.total} 项`);}catch(e){if(epoch===generation)treeNote(e.message,true);}}
 function render(){tree.replaceChildren();const visited=new Set();function append(dir,holder,depth){if(depth>30||visited.has(dir))return;visited.add(dir);const data=cache.get(dir);if(!data)return;for(const item of data.entries){const row=el('div','file-tree-row');row.style.setProperty('--file-depth',depth);row.title=item.name+' · '+item.mode;const isDir=item.kind==='directory';const expander=button(isDir?(expanded.has(item.path)?'▾':'▸'):'',isDir?'展开或折叠 '+item.name:item.name,async()=>{if(!isDir)return;if(expanded.has(item.path)){expanded.delete(item.path);render();}else if(cache.has(item.path)){expanded.add(item.path);render();}else await load(item.path);});expander.className='file-expand';if(!isDir){expander.disabled=true;expander.tabIndex=-1;}
 const target=button('',(isDir?'打开目录 ':'打开文件 ')+item.name,()=>isDir?load(item.path,{navigate:true}):open(item.path));target.className='file-tree-target';target.append(icon(item.kind),el('span','file-tree-name',item.name));if(item.kind==='link')target.append(el('span','file-link-mark','↗'));row.append(expander,target);holder.append(row);if(isDir&&expanded.has(item.path))append(item.path,holder,depth+1);}
 if(data.nextOffset>=0){const more=button('加载更多','加载更多 '+dir,()=>load(dir,{offset:data.nextOffset}));more.className='file-load-more';holder.append(more);}if(!data.entries.length)holder.append(el('p','file-empty','目录为空'));}
 append(root,tree,0);}
 const discard=$('#file-discard-dialog');
 function resolveDiscard(value){if(discard.open)discard.close();const resolve=confirmResolve;confirmResolve=null;resolve?.(value);}
 async function confirmDiscard(){if(saving){note('正在保存，请等待操作完成。',true);return false;}if(!dirty())return true;if(confirmResolve)return false;discard.showModal();return new Promise(resolve=>{confirmResolve=resolve;$('#file-keep-editing').focus();});}
 $('#file-keep-editing').addEventListener('click',()=>resolveDiscard(false));$('#file-discard-confirm').addEventListener('click',()=>resolveDiscard(true));discard.addEventListener('cancel',e=>{e.preventDefault();resolveDiscard(false);});
 function show(data){current=data;input.value=data.content;baseline=input.value;input.readOnly=data.readOnly;input.disabled=false;$('#file-name').textContent=data.path;$('#file-name').title=data.path;$('#file-tab-label').textContent=data.path.split('/').pop()||'/';$('#file-tab').hidden=false;$('#file-close').hidden=false;note(data.readOnly?data.reason:'');summary();view('file');if(matchMedia('(max-width:700px)').matches)setSidebar(false);}
 async function open(path){if(opening||saving)return;if(!await confirmDiscard())return;const epoch=generation;opening=true;treeNote('正在读取文件…');try{const data=await request('read',path);if(epoch!==generation)return;if(data.kind==='directory'){root=data.path;pathInput.value=root;cache.set(root,data);expanded.add(root);render();treeNote(`${data.total} 项`);return;}show(data);treeNote('');}catch(e){if(epoch===generation){treeNote(e.message,true);if(!editor.hidden)note(e.message,true);}}finally{if(epoch===generation)opening=false;}}
 async function save(){if(!current||!dirty()||saving||current.readOnly||!active)return;const epoch=generation,target=current;const payload=input.value;saving=true;input.disabled=true;summary();note('正在保存…');try{const data=await request('save',target.requestedPath,{revision:target.revision,content:payload});if(epoch===generation){show(data);note('已保存');}}catch(e){if(epoch===generation)note(e.message,true);}finally{if(epoch===generation){saving=false;input.disabled=false;summary();}}}
 $('#file-save').addEventListener('click',save);$('#file-reload').addEventListener('click',()=>current&&open(current.requestedPath));input.addEventListener('input',()=>{if(!saving)note(dirty()?'尚未保存':'');summary();});input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();}if(e.key==='Tab'&&!e.shiftKey&&!e.ctrlKey&&!e.metaKey&&!input.readOnly){e.preventDefault();input.setRangeText('  ',input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input'));}});
 $('#file-wrap').addEventListener('change',e=>{input.wrap=e.target.checked?'soft':'off';});
 toggle.addEventListener('click',()=>{if(active)setSidebar(sidebar.hidden);});$('#file-sidebar-close').addEventListener('click',()=>setSidebar(false));$('#file-drawer-shade').addEventListener('click',()=>setSidebar(false));$('#file-location-form').addEventListener('submit',e=>{e.preventDefault();const value=pathInput.value.trim();if(value.startsWith('/'))load(value,{navigate:true});else treeNote('请输入以 / 开头的完整路径',true);});
 $('#file-root').addEventListener('click',()=>load('/',{navigate:true}));$('#file-home').addEventListener('click',()=>load('/',{navigate:true,action:'home'}));$('#file-up').addEventListener('click',()=>load(root.split('/').slice(0,-1).join('/')||'/',{navigate:true}));$('#file-refresh').addEventListener('click',()=>{cache.clear();expanded.clear();load(root,{navigate:true});});
 $('#terminal-tab').addEventListener('click',()=>view('terminal'));$('#file-tab').addEventListener('click',()=>view('file'));$('#file-close').addEventListener('click',async()=>{if(!await confirmDiscard())return;current=null;input.value='';baseline='';$('#file-tab').hidden=true;$('#file-close').hidden=true;view('terminal');});
 const separator=$('#file-resizer');let resizing=false;const width=value=>{const n=Math.max(200,Math.min(420,dialog.clientWidth*.48,value));dialog.style.setProperty('--file-width',n+'px');separator.setAttribute('aria-valuenow',String(Math.round(n)));onResize();};separator.addEventListener('pointerdown',e=>{if(!active)return;resizing=true;separator.setPointerCapture(e.pointerId);e.preventDefault();});separator.addEventListener('pointermove',e=>{if(resizing)width(e.clientX-dialog.getBoundingClientRect().left);});separator.addEventListener('pointerup',()=>{resizing=false;});separator.addEventListener('lostpointercapture',()=>{resizing=false;});separator.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();width(sidebar.clientWidth+(e.key==='ArrowLeft'?-20:20));}});
 window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
 function clear(){generation++;active=false;saving=false;opening=false;current=null;baseline='';input.value='';input.disabled=false;input.readOnly=false;cache.clear();expanded.clear();tree.replaceChildren();root='/';pathInput.value='/';for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('SSH 连接已结束'));}pending.clear();toggle.disabled=true;setSidebar(false);$('#file-tab').hidden=true;$('#file-close').hidden=true;$('#file-name').textContent='';$('#file-meta').textContent='';note('');treeNote('连接 SSH 后浏览文件');resolveDiscard(false);view('terminal');}
 function ready(supported){clear();if(!supported){treeNote('当前主控版本尚未启用文件功能');return;}active=true;toggle.disabled=false;setSidebar(!matchMedia('(max-width:700px)').matches);load('/',{navigate:true});}
 clear();return {ready,receive,clear,confirmDiscard,showTerminal:()=>view('terminal'),isDirty:dirty};
}
