import {terminalAppearance} from './terminal-appearance.mjs';
import {createTerminalKeys} from './terminal-keys.mjs';
import {SearchAddon} from './addon-search.mjs';
import {createFileBrowser} from './files.mjs';
import {Terminal} from './xterm.mjs';
import {FitAddon} from './addon-fit.mjs';
function createSession(api,root,dialog,onClose){
 const $=s=>root.querySelector(s),mount=$('#terminal-mount'),placeholder=$('.terminal-placeholder'),connect=$('#terminal-connect'),disconnect=$('#terminal-disconnect');
 let socket=null,term=null,fit=null,search=null,sendInput=()=>{},resize=null,current=null,generation=0,connected=false,commands=[],retained='',retryTimer=null,retries=0,ended=false;
 const restore=document.createElement('select');restore.className='terminal-restore';restore.setAttribute('aria-label','选择新建或恢复终端');restore.append(new Option('新建会话',''));connect.before(restore);
 const detach=document.createElement('button');detach.type='button';detach.textContent='保留并退出';detach.disabled=true;disconnect.after(detach);disconnect.textContent='结束会话';
 restore.onchange=()=>{retained=restore.value;connect.textContent=retained?'恢复会话':'连接';};
 async function choices(){try{const r=await api('/api/admin/terminal-sessions');restore.replaceChildren(new Option('新建会话',''));for(const s of r.sessions.filter(s=>s.node===current?.public.id&&!s.attached))restore.append(new Option('恢复 · '+new Date(s.created*1000).toLocaleTimeString('zh-CN',{hour12:false}),s.id));restore.value=retained;}catch(e){hint(e.message);}}
 async function end(keep=false,notify=true){clearTimeout(retryTimer);retryTimer=null;ended=true;if(retained&&!keep&&notify){await api('/api/admin/terminal-sessions','POST',{id:retained});}if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:keep?'detach':'close'}));if(!keep){retained='';files.end?.();}stop(true);}

 const state=(value,ready=false)=>{const dot=document.createElement('i');dot.className='status-dot '+(ready?'online':'offline');$('#terminal-state').replaceChildren(dot,document.createTextNode(value));$('#terminal-footer-state').textContent='WSS · '+value;};
 const hint=value=>{$('#terminal-hint').textContent=value;};
 function stop(clear=false){clearTimeout(retryTimer);retryTimer=null;keys.ready(false);sendInput=()=>{};files.suspend?.();$('#terminal-paste').disabled=true;closePaste();$('#terminal-run-command').disabled=true;generation++;connected=false;if(socket){socket.onclose=null;socket.close(1000,'closed');socket=null;}resize?.disconnect();resize=null;connect.disabled=false;disconnect.disabled=true;detach.disabled=true;restore.disabled=false;state('已断开');if(clear){term?.dispose();term=null;fit=null;mount.replaceChildren();mount.hidden=true;placeholder.hidden=false;hint('点击连接建立终端会话。');}else if(term){term.options.disableStdin=true;}}
 function open(record){stop(true);current=record;$('#terminal-title').textContent=record.public.name;$('#terminal-target').textContent=record.username+'@'+record.ip+':'+record.port;state('未连接');hint(record.demo?'演示节点暂不支持 SSH。':record.public.online?'点击连接建立终端会话。':'节点暂未在线，可在上线后点击连接重试。');connect.disabled=record.demo;if(!dialog.open)dialog.showModal();connect.focus();loadCommands();choices();}
 async function start(){if(!current||!dialog.open)return;ended=false;retained=retained||restore.value;stop(true);const run=generation;connect.disabled=true;hint('正在请求终端授权…');state('连接中');
  try{const result=await api('/api/admin/terminal-ticket','POST',{id:current.public.id});if(run!==generation||!dialog.open)return;
   term=new Terminal({fontFamily:'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',fontSize:13,lineHeight:1.25,scrollback:2000,cursorBlink:true,allowProposedApi:false,disableStdin:true,allowTransparency:true,theme:terminalAppearance()});fit=new FitAddon();term.loadAddon(fit);search=new SearchAddon();term.loadAddon(search);
   // Block terminal-controlled links, clipboard access and window operations.
   term.parser.registerOscHandler(52,()=>true);term.parser.registerOscHandler(8,()=>true);term.parser.registerOscHandler(0,()=>true);term.parser.registerOscHandler(2,()=>true);
   placeholder.hidden=true;mount.hidden=false;term.open(mount);fit.fit();
   socket=new WebSocket(new URL('/api/terminal',location.href).href.replace(/^https:/,'wss:'));socket.binaryType='arraybuffer';const ws=socket;
   const send=(data)=>{if(ws.readyState===WebSocket.OPEN)ws.send(data);};
   const input=data=>{if(!connected||ws.readyState!==WebSocket.OPEN)return;if(ws.bufferedAmount>128*1024){stop();hint('输入过快，连接已关闭。');return;}for(let i=0;i<data.length;i+=16384)send(data.slice(i,i+16384));};
   sendInput=value=>input(new TextEncoder().encode(value));term.onData(value=>sendInput(keys.transform(value)));term.onBinary(value=>input(Uint8Array.from(value,c=>c.charCodeAt(0)&255)));
   term.onResize(({cols,rows})=>{if(connected)send(JSON.stringify({type:'resize',cols,rows}));});resize=new ResizeObserver(()=>{if(dialog.open&&term&&mount.getClientRects().length)fit.fit();});resize.observe(mount);
   ws.onopen=()=>send(JSON.stringify({type:'authorize',ticket:result.ticket,resume:retained,cols:term.cols,rows:term.rows}));
   ws.onmessage=event=>{if(run!==generation)return;if(typeof event.data==='string'){let message;try{message=JSON.parse(event.data);}catch{stop();return;}if(message.type==='file_result'){files.receive(message);return;}if(message.type==='ready'){connected=true;retries=0;retained=message.session||'';restore.disabled=true;detach.disabled=!retained;keys.ready(message.terminal!==false);files.ready(message.files===true,{session:message.transferSession||retained,node:current.public.id});hint(retained?'意外断线保留 30 分钟；关闭按钮结束会话。':'当前为普通会话。服务器安装 tmux 后，新建终端即可启用保活和续传。');$('#terminal-paste').disabled=message.terminal===false;term.options.disableStdin=message.terminal===false;disconnect.disabled=false;$('#terminal-run-command').disabled=!$('#terminal-command').value;state('已连接',true);term.focus();}else if(message.type==='error'){state(message.error||message.message||'连接失败');term.write('\r\n连接未完成，请重新连接。\r\n');}else if(message.type==='notice'){term.write('\r\n'+message.message+'\r\n');}else if(message.type==='closed'){ended=true;retained='';state('会话已结束');}}else{term.write(new Uint8Array(event.data),()=>send(JSON.stringify({type:'ack'})));}};
   ws.onerror=()=>state('连接异常');ws.onclose=()=>{if(run!==generation)return;connected=false;keys.ready(false);sendInput=()=>{};files.suspend?.();$('#terminal-paste').disabled=true;closePaste();$('#terminal-run-command').disabled=true;connect.disabled=false;disconnect.disabled=true;term.options.disableStdin=true;state(retained&&!ended?'连接中断 · 会话已保留':'已断开');connect.textContent=retained?'恢复会话':'连接';resize?.disconnect();if(retained&&!ended&&retries<5){const delay=[1500,3000,7000,15000,30000][retries++];retryTimer=setTimeout(()=>{if(dialog.open&&retained&&!ended)start();},delay);}};
  }catch(error){if(run===generation){hint(error.message);state('连接失败');connect.disabled=false;}}
 }
 async function loadCommands(){const select=$('#terminal-command');select.replaceChildren(new Option('加载中…',''));$('#terminal-command-preview').textContent='';commands=[];try{const result=await api('/api/admin/commands');if(!dialog.open)return;commands=result.commands;select.replaceChildren(new Option(commands.length?'选择命令':'暂无常用命令',''));for(const c of commands)select.append(new Option(c.name,c.id));}catch{select.replaceChildren(new Option('命令加载失败',''));}}
 $('#terminal-command').addEventListener('change',()=>{const c=commands.find(c=>c.id===$('#terminal-command').value);$('#terminal-command-preview').textContent=c?.script.split('\n')[0]||'';$('#terminal-command-preview').title=c?.script||'';$('#terminal-run-command').disabled=!connected||!c;});
 $('#terminal-run-command').addEventListener('click',()=>{const id=$('#terminal-command').value;if(!connected||!id||socket?.readyState!==WebSocket.OPEN)return;socket.send(JSON.stringify({type:'command',id}));term.focus();});
 function closePaste(){const d=$('#terminal-paste-dialog');if(d.open)d.close();$('#terminal-paste-input').value='';$('#paste-error').textContent='';}
 $('#terminal-paste').addEventListener('click',()=>{if(!connected)return;$('#paste-error').textContent='';$('#terminal-paste-dialog').showModal();$('#terminal-paste-input').focus();});
 $('#paste-close').addEventListener('click',closePaste);$('#paste-cancel').addEventListener('click',closePaste);$('#terminal-paste-dialog').addEventListener('close',()=>{$('#terminal-paste-input').value='';});
 $('#terminal-paste-form').addEventListener('submit',event=>{event.preventDefault();const script=$('#terminal-paste-input').value.replace(/\r\n?/g,'\n').trimEnd();const bytes=new TextEncoder().encode(script+'\n');if(!script.trim()){return;}if(bytes.length>8192||/[\x00-\x08\x0b-\x1f\x7f]/.test(script)){$('#paste-error').textContent='命令最多 8192 字节，且不能含特殊控制字符。';return;}if(!connected||socket?.readyState!==WebSocket.OPEN){$('#paste-error').textContent='连接已断开，请重新连接。';return;}if(socket.bufferedAmount>128*1024){$('#paste-error').textContent='正在发送其他内容，请稍后重试。';return;}socket.send(bytes);closePaste();term.focus();});
 connect.addEventListener('click',()=>{retries=0;start();});disconnect.addEventListener('click',async()=>{if(await files.confirmDiscard())try{await end(false);await choices();}catch(e){hint(e.message);}});detach.addEventListener('click',()=>onClose(true));$('#terminal-close').addEventListener('click',onClose);$('#terminal-maximize').addEventListener('click',()=>{const active=dialog.classList.toggle('is-expanded');$('#terminal-maximize').setAttribute('aria-pressed',String(active));$('#terminal-maximize').textContent=active?'还原':'展开';requestAnimationFrame(()=>fit?.fit());});
 const keys=createTerminalKeys({root,getTerm:()=>term,getSearch:()=>search,send:value=>sendInput(value),paste:()=>$('#terminal-paste').click(),fit:()=>requestAnimationFrame(()=>fit?.fit())});
 const appearanceObserver=new MutationObserver(()=>{if(term)term.options.theme=terminalAppearance();});appearanceObserver.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme','data-appearance','style']});
 const files=createFileBrowser({dialog,scope:root,send:value=>{if(!connected||socket?.readyState!==WebSocket.OPEN)throw Error('SSH 连接已断开');if(socket.bufferedAmount>128*1024)throw Error('正在发送其他内容，请稍后重试');socket.send(value);},onResize:()=>{if(term&&mount.getClientRects().length)fit?.fit();},onTerminal:()=>{if(connected)term?.focus();}});
 return {open,confirm:(keep=false)=>files.confirmDiscard(keep),fit:()=>{if(term&&mount.getClientRects().length)fit?.fit();},deactivate:()=>keys.reset(),destroy:async(keep=false,force=false)=>{try{await end(keep,!force);}catch(e){if(!force)throw e;}appearanceObserver.disconnect();stop(true);keys.destroy();files.destroy({keep});current=null;}};
}

export function createTerminalUI(api,getRecords,toast){
 const dialog=document.querySelector('#terminal-dialog'),shell=dialog.querySelector('.terminal-shell').cloneNode(true);
 const paste=document.querySelector('#terminal-paste-dialog').cloneNode(true),discard=document.querySelector('#file-discard-dialog').cloneNode(true);
 document.querySelector('#terminal-paste-dialog').remove();document.querySelector('#file-discard-dialog').remove();
 const bar=document.createElement('div');bar.className='ssh-session-bar';const tabs=document.createElement('div');tabs.className='ssh-session-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','SSH 会话');
 const select=document.createElement('select');select.setAttribute('aria-label','新增 SSH 会话');const add=document.createElement('button');add.type='button';add.textContent='新建标签';
 const stage=document.createElement('div');stage.className='ssh-session-stage';bar.append(tabs,select,add);dialog.replaceChildren(bar,stage);
 let active=null,next=0,closing=false;const sessions=new Map();
 const viewport=window.visualViewport;
 function sizeViewport(){if(!dialog.open)return;const mobile=matchMedia('(max-width:700px)').matches;dialog.classList.toggle('is-compact-terminal',mobile&&!!viewport&&viewport.height<500);if(mobile&&viewport){dialog.style.height=Math.max(180,viewport.height-16)+'px';dialog.style.maxHeight=Math.max(180,viewport.height-16)+'px';dialog.style.top=(viewport.offsetTop+8)+'px';dialog.style.marginTop='0';}else{for(const p of ['height','max-height','top','margin-top'])dialog.style.removeProperty(p);}requestAnimationFrame(()=>sessions.get(active)?.ui?.fit());}
 viewport?.addEventListener('resize',sizeViewport);viewport?.addEventListener('scroll',sizeViewport);window.addEventListener('resize',sizeViewport);
 function draw(){tabs.replaceChildren();let number=0;for(const [id,s]of sessions){number++;const wrap=document.createElement('div');wrap.className='ssh-session-tab'+(id===active?' active':'');const b=document.createElement('button');b.type='button';b.textContent=s.record.public.name+' · '+number;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(id===active));b.onclick=()=>activate(id);const x=document.createElement('button');x.type='button';x.textContent='×';x.setAttribute('aria-label','关闭会话 '+number);x.onclick=()=>remove(id);wrap.append(b,x);tabs.append(wrap);}const chosen=select.value;select.replaceChildren(new Option('选择服务器',''));for(const r of getRecords().filter(r=>!r.removing&&r.public.online))select.append(new Option(r.public.name,r.public.id));select.value=chosen;add.disabled=sessions.size>=4;add.title='最多同时打开 4 个标签';}
 function activate(id){const s=sessions.get(id);if(!s)return;sessions.get(active)?.ui?.deactivate();active=id;stage.replaceChildren(s.root);sizeViewport();dialog.classList.toggle('files-visible',!s.root.querySelector('#file-sidebar').hidden);draw();requestAnimationFrame(()=>s.ui.fit());}
 async function remove(id,keep=false){const s=sessions.get(id);if(!s)return;activate(id);if(!await s.ui.confirm(keep))return;try{await s.ui.destroy(keep);}catch(e){toast(e.message,true);return;}sessions.delete(id);if(sessions.size)activate(sessions.keys().next().value);else{active=null;stage.replaceChildren();dialog.close();}draw();}
 function open(record,force=false){if(!force){const found=[...sessions].find(([,s])=>s.record.public.id===record.public.id);if(found){activate(found[0]);if(!dialog.open)dialog.showModal();return;}}if(sessions.size>=4){toast('最多同时打开 4 个 SSH 标签',true);return;}sessions.get(active)?.ui?.deactivate();const id=++next,root=document.createElement('div');root.className='ssh-session';root.append(shell.cloneNode(true),paste.cloneNode(true),discard.cloneNode(true));const s={root,record,ui:null};sessions.set(id,s);active=id;stage.replaceChildren(root);if(!dialog.open)dialog.showModal();s.ui=createSession(api,root,dialog,keep=>remove(id,keep===true));s.ui.open(record);draw();sizeViewport();}
 async function close(force=false){for(const [id,s]of sessions){try{await s.ui.destroy(false,force);}catch(e){activate(id);toast('结束会话未确认：'+e.message,true);return;}sessions.delete(id);}active=null;stage.replaceChildren();dialog.close();draw();}
 // File-picker cancel events bubble; only this dialog may close the SSH workspace.
 dialog.addEventListener('cancel',async e=>{if(e.target!==dialog)return;e.preventDefault();if(closing)return;closing=true;try{for(const [id,s]of sessions){activate(id);if(!await s.ui.confirm())return;}await close();}finally{closing=false;}});
 dialog.addEventListener('close',e=>{if(e.target===dialog&&sessions.size)close(true);});
 add.onclick=()=>{const r=getRecords().find(r=>r.public.id===select.value);if(r)open(r,true);else select.focus();};
 return {open,close};
}
