import {createFileBrowser} from './files.mjs';
import {Terminal} from './xterm.mjs';
import {FitAddon} from './addon-fit.mjs';
export function createTerminalUI(api){
 const $=s=>document.querySelector(s),dialog=$('#terminal-dialog'),mount=$('#terminal-mount'),placeholder=$('.terminal-placeholder'),connect=$('#terminal-connect'),disconnect=$('#terminal-disconnect');
 let socket=null,term=null,fit=null,resize=null,current=null,generation=0,connected=false,commands=[];
 const state=(value,ready=false)=>{const dot=document.createElement('i');dot.className='status-dot '+(ready?'online':'offline');$('#terminal-state').replaceChildren(dot,document.createTextNode(value));$('#terminal-footer-state').textContent='WSS · '+value;};
 const hint=value=>{$('#terminal-hint').textContent=value;};
 function stop(clear=false){files.clear();$('#terminal-paste').disabled=true;closePaste();$('#terminal-run-command').disabled=true;generation++;connected=false;if(socket){socket.onclose=null;socket.close(1000,'closed');socket=null;}resize?.disconnect();resize=null;connect.disabled=false;disconnect.disabled=true;state('已断开');if(clear){term?.dispose();term=null;fit=null;mount.replaceChildren();mount.hidden=true;placeholder.hidden=false;hint('点击连接建立终端会话。');}else if(term){term.options.disableStdin=true;}}
 function open(record){stop(true);current=record;$('#terminal-title').textContent=record.public.name;$('#terminal-target').textContent=record.username+'@'+record.ip+':'+record.port;state('未连接');hint(record.demo?'演示节点暂不支持 SSH。':record.public.online?'点击连接建立终端会话。':'Agent 未在线，请先完成部署。');connect.disabled=record.demo||!record.public.online;dialog.showModal();connect.focus();loadCommands();}
 async function start(){if(!current||!dialog.open)return;stop(true);const run=generation;connect.disabled=true;hint('正在请求终端授权…');state('连接中');
  try{const result=await api('/api/admin/terminal-ticket','POST',{id:current.public.id});if(run!==generation||!dialog.open)return;
   term=new Terminal({fontFamily:'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',fontSize:13,lineHeight:1.25,scrollback:2000,cursorBlink:true,allowProposedApi:false,disableStdin:true,theme:{background:'#121b29',foreground:'#dce6f0',cursor:'#b9dbef',selectionBackground:'#406584'}});fit=new FitAddon();term.loadAddon(fit);
   // Block terminal-controlled links, clipboard access and window operations.
   term.parser.registerOscHandler(52,()=>true);term.parser.registerOscHandler(8,()=>true);term.parser.registerOscHandler(0,()=>true);term.parser.registerOscHandler(2,()=>true);
   placeholder.hidden=true;mount.hidden=false;term.open(mount);fit.fit();
   socket=new WebSocket(new URL('/api/terminal',location.href).href.replace(/^https:/,'wss:'));socket.binaryType='arraybuffer';const ws=socket;
   const send=(data)=>{if(ws.readyState===WebSocket.OPEN)ws.send(data);};
   const input=data=>{if(!connected||current?.policy?.terminal===false||ws.readyState!==WebSocket.OPEN)return;if(ws.bufferedAmount>128*1024){stop();hint('输入过快，连接已关闭。');return;}for(let i=0;i<data.length;i+=16384)send(data.slice(i,i+16384));};
   term.onData(value=>input(new TextEncoder().encode(value)));term.onBinary(value=>input(Uint8Array.from(value,c=>c.charCodeAt(0)&255)));
   term.onResize(({cols,rows})=>{if(connected)send(JSON.stringify({type:'resize',cols,rows}));});resize=new ResizeObserver(()=>{if(dialog.open&&term&&mount.getClientRects().length)fit.fit();});resize.observe(mount);
   ws.onopen=()=>send(JSON.stringify({type:'authorize',ticket:result.ticket,cols:term.cols,rows:term.rows}));
   ws.onmessage=event=>{if(run!==generation)return;if(typeof event.data==='string'){let message;try{message=JSON.parse(event.data);}catch{stop();return;}if(message.type==='file_result'){files.receive(message);return;}if(message.type==='ready'){connected=true;files.ready(message.files===true);$('#terminal-paste').disabled=message.terminal===false;term.options.disableStdin=message.terminal===false;disconnect.disabled=false;$('#terminal-run-command').disabled=current?.policy?.terminal===false||!$('#terminal-command').value;state('已连接',true);term.focus();}else if(message.type==='error'){state(message.error||message.message||'连接失败');term.write('\r\n连接未完成，请重新连接。\r\n');}else if(message.type==='notice'){term.write('\r\n'+message.message+'\r\n');}else if(message.type==='closed'){state('会话已结束');}}else{term.write(new Uint8Array(event.data),()=>send(JSON.stringify({type:'ack'})));}};
   ws.onerror=()=>state('连接异常');ws.onclose=()=>{if(run!==generation)return;connected=false;files.clear();$('#terminal-paste').disabled=true;closePaste();$('#terminal-run-command').disabled=true;connect.disabled=false;disconnect.disabled=true;term.options.disableStdin=true;state('已断开');resize?.disconnect();};
  }catch(error){if(run===generation){hint(error.message);state('连接失败');connect.disabled=false;}}
 }
 async function loadCommands(){const select=$('#terminal-command');select.replaceChildren(new Option('加载中…',''));$('#terminal-command-preview').textContent='';commands=[];try{const result=await api('/api/admin/commands');if(!dialog.open)return;commands=result.commands;select.replaceChildren(new Option(commands.length?'选择命令':'暂无常用命令',''));for(const c of commands)select.append(new Option(c.name,c.id));}catch{select.replaceChildren(new Option('命令加载失败',''));}}
 $('#terminal-command').addEventListener('change',()=>{const c=commands.find(c=>c.id===$('#terminal-command').value);$('#terminal-command-preview').textContent=c?.script.split('\n')[0]||'';$('#terminal-command-preview').title=c?.script||'';$('#terminal-run-command').disabled=!connected||!c||current?.policy?.terminal===false;});
 $('#terminal-run-command').addEventListener('click',()=>{const id=$('#terminal-command').value;if(!connected||!id||socket?.readyState!==WebSocket.OPEN)return;socket.send(JSON.stringify({type:'command',id}));term.focus();});
 function closePaste(){const d=$('#terminal-paste-dialog');if(d.open)d.close();$('#terminal-paste-input').value='';$('#paste-error').textContent='';}
 $('#terminal-paste').addEventListener('click',()=>{if(!connected)return;$('#paste-error').textContent='';$('#terminal-paste-dialog').showModal();$('#terminal-paste-input').focus();});
 $('#paste-close').addEventListener('click',closePaste);$('#paste-cancel').addEventListener('click',closePaste);$('#terminal-paste-dialog').addEventListener('close',()=>{$('#terminal-paste-input').value='';});
 $('#terminal-paste-form').addEventListener('submit',event=>{event.preventDefault();const script=$('#terminal-paste-input').value.replace(/\r\n?/g,'\n').trimEnd();const bytes=new TextEncoder().encode(script+'\n');if(!script.trim()){return;}if(bytes.length>8192||/[\x00-\x08\x0b-\x1f\x7f]/.test(script)){$('#paste-error').textContent='命令最多 8192 字节，且不能含特殊控制字符。';return;}if(!connected||socket?.readyState!==WebSocket.OPEN){$('#paste-error').textContent='连接已断开，请重新连接。';return;}if(socket.bufferedAmount>128*1024){$('#paste-error').textContent='正在发送其他内容，请稍后重试。';return;}socket.send(bytes);closePaste();term.focus();});
 connect.addEventListener('click',start);disconnect.addEventListener('click',async()=>{if(await files.confirmDiscard())stop();});dialog.addEventListener('close',()=>{stop(true);current=null;commands=[];$('#terminal-command').replaceChildren();$('#terminal-command-preview').textContent='';$('#terminal-command-preview').title='';$('#terminal-target').textContent='';});$('#terminal-close').addEventListener('click',async()=>{if(await files.confirmDiscard())dialog.close();});dialog.addEventListener('cancel',event=>{if(files.isDirty()){event.preventDefault();files.confirmDiscard().then(ok=>{if(ok)dialog.close();});}});$('#terminal-maximize').addEventListener('click',()=>{const active=dialog.classList.toggle('is-expanded');$('#terminal-maximize').setAttribute('aria-pressed',String(active));$('#terminal-maximize').textContent=active?'还原':'展开';requestAnimationFrame(()=>fit?.fit());});
 const files=createFileBrowser({dialog,send:value=>{if(!connected||socket?.readyState!==WebSocket.OPEN)throw Error('SSH 连接已断开');if(socket.bufferedAmount>128*1024)throw Error('正在发送其他内容，请稍后重试');socket.send(value);},onResize:()=>{if(term&&mount.getClientRects().length)fit?.fit();},onTerminal:()=>{if(connected)term?.focus();}});
 return {open,close:()=>{dialog.close();stop(true);current=null;}};
}
